server:
  port: 8800

spring:
  application:
    name: mall-member
  datasource:
    username: root
    password: Fantastu7.
    url: jdbc:mysql://localhost:3306/mall_ums?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

    sentinel:
      transport:
        # 应用开启端口，接收dashboard限流规则，如果被占用会默认+1
        port: 8719
        #配置sentinel dashboard地址
        dashboard: localhost:8333

  redis:
    port: 6379
    host: localhost


  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  session:
    store-type: redis


#开启feign对sentinel的支持
feign:
  sentinel:
    enabled: true
  # feign调用超时时间配置 zjy
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 600000



mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml

  global-config:
    db-config:
      id-type: auto


#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'

