server:
  port: 88
spring:
  application:
    name: mall-gateway
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        sentinel:
          transport:
            # 应用开启端口，接收dashboard限流规则，如果被占用会默认+1
            port: 8719
            # 控制台ip:port
            dashboard: 127.0.0.1:8333

    gateway:
      routes:
        #先拦截到的后面不会在拦截，所以精确的高优先级写前面
        ## http://localhost:88/api/product/category/list/tree http://localhost:10000/product/category/list/tree
        ## http://localhost:88/api/captcha.jpg   http://localhost:8080/renren-fast/captcha.jpg
        #        - id: test_route
        #          uri: https://www.baidu.com
        #          predicates:
        #            - Query=uri,baidu
        #
        #        - id: qq_route
        #          uri: https://www.qq.com
        #          predicates:

        #            - Query=uri,qq
        ## 前端项目，/api
        #lb load banance负载均衡  filter路径重写

        - id: product_route
          uri: lb://mall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        - id: coupon_route
          uri: lb://mall-coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        - id: third_party_route
          uri: lb://mall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>/?.*),/$\{segment}

        - id: member_route
          uri: lb://mall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        - id: ware_route
          uri: lb://mall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        - id: order_route
          uri: lb://mall-order
          predicates:
            - Path=/api/order/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /renren-fast/$\{segment}

        #监听host
        - id: mall_host_route
          uri: lb://mall-product
          predicates:
            - Host=mall.com,item.mall.com

        - id: mall_search_route
          uri: lb://mall-search
          predicates:
            - Host=search.mall.com

        - id: mall_auth_route
          uri: lb://mall-auth-server
          predicates:
            - Host=auth.mall.com

        - id: mall_cart_route
          uri: lb://mall-cart
          predicates:
            - Host=cart.mall.com

        - id: mall_order_route
          uri: lb://mall-order
          predicates:
            - Host=order.mall.com

        - id: mall_member_route
          uri: lb://mall-member
          predicates:
            - Host=member.mall.com


        - id: mall_seckill_route
          uri: lb://mall-seckill
          predicates:
            - Host=seckill.mall.com

#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'