server:
  port: 40000


spring:
  application:
    name: mall-cart

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

    sentinel:
      transport:
        # 应用开启端口，接收dashboard限流规则，如果被占用会默认+1
        port: 8719
        #配置sentinel dashboard地址
        dashboard: localhost:8333

  redis:
    port: 6379
    host: 121.43.231.169
  session:
    store-type: redis


#开启feign对sentinel的支持
feign:
  sentinel:
    enabled: true
# feign调用超时时间配置 zjy
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 600000

#配置线程池
mall:
  thread:
    coreSize: 20
    maxSize: 200
    keepAliveTime: 10

#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'


