server:
  port: 10000
  servlet:
    session:
      timeout: 30m

spring:
  application:
    name: mall-product
  datasource:
    username: root
    password: Fantastu7.
    url: jdbc:mysql://localhost:3306/mall_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    #不知道在那里用到了。。。。。。。。。
    alicloud:
      access-key: LTAI5tGFM1cGP2afwpQFfnyL
      secret-key: QLcPP7HaQkvJCeYdSkSLy7Vq2aD0AN
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: gulimall-fantastzjy

    sentinel:
      transport:
        # 应用开启端口，接收dashboard限流规则，如果被占用会默认+1
        port: 8719
        #配置sentinel dashboard地址
        dashboard: localhost:8333

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  cache:
    type: redis # 使用redis作为缓存
    redis:
      time-to-live: 3600s # 过期时间
      # key-prefix: CACHE_ # 会导致自己在@Cacheable里设置的名字失效，所以这里不指定
      use-key-prefix: true # key值加前缀
      cache-null-values: true # 缓存控制
  session:
    store-type: redis

#开启feign对sentinel的支持
feign:
  sentinel:
    enabled: true

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  #设置实体类的自增主键
  global-config:
    db-config:
      id-type: auto
      #逻辑删除
      logic-delete-value: 1
      logic-not-delete-value: 0

logging:
  level:
    com.mall: error        #日志级别为debug会打印sql语句   这个包下的com.mall


##暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'


mall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10