server:
  port: 12000

spring:
  application:
    name: mall-search
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

    sentinel:
      transport:
        # 应用开启端口，接收dashboard限流规则，如果被占用会默认+1
        port: 8719
        #配置sentinel dashboard地址
        dashboard: localhost:8333

  redis:
    host: 121.43.231.169
    port: 6379

  thymeleaf:
    cache: false

  session:
    store-type: redis

elasticsearch:
  host: 121.43.231.169


#开启feign对sentinel的支持
feign:
  sentinel:
    enabled: true



logging:
  level:
    com.mall.search: debug
    root: warn
  pattern:
    console: "%d{yyyy-MM-dd} [%thread] - %msg%n"

#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
