spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tGFM1cGP2afwpQFfnyL
      secret-key: QLcPP7HaQkvJCeYdSkSLy7Vq2aD0AN
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: gulimall-fantastzjy

#      sms:
#        host: https://fesms.market.alicloudapi.com
#        path: /sms/
#        skin: 1
#        sign: 175622
#        appcode: b0563c23aff8428c97a54d4f7f9e28e5


  application:
    name: mall-third-party

server:
  port: 30000